apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ceph-public-net
  namespace: rook-ceph
spec:
  config: '{
        "cniVersion": "0.3.1",
        "type": "macvlan",
        "master": "ens4",
        "mode": "bridge",
        "ipam": {
          "type": "whereabouts",
          "range": "192.168.10.0/24"
        }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ceph-cluster-net
  namespace: rook-ceph
spec:
  config: '{
        "cniVersion": "0.3.1",
        "type": "macvlan",
        "master": "ens5",
        "mode": "bridge",
        "ipam": {
          "type": "whereabouts",
          "range": "192.168.20.0/24"
        }
    }'
